# SEARCH FUNCTIONS

# Functions to generate URLs and call APIs

# Generics

#' Pick out nodes from xml and turn it into a tibble
#' 
#' @param xmlnode an xml node containing nodes
#' @param nodenames the names of the nodes you wish to extract (string with nodes separated by commas)
#' @import dplyr
#' @import tidyr
#' @importFrom xml2 xml_text xml_name
#' @return A tibble with node names as col names and node text as values
#'  

xml2tib <- function(xmlnode, nodenames) {
  
  values <- xmlnode  %>%
    xml_nodes(nodenames) %>% 
    xml2::xml_text() %>% 
    as_tibble()
  
  fields <- xmlnode %>% 
    xml_nodes(nodenames) %>% 
    xml_name() %>% 
    as_tibble() %>% 
    rename(field = value)
  
  bind_cols(values, fields) %>% 
    group_by(field) %>% 
    mutate(value = paste0(value, collapse = " ; ")) %>% 
    unique() %>% 
    ungroup() 
  
}
  
# Pubmed

#' Generates URL for pubmed API
#'
#' @param searchterm text of the query
#' @param startdate from date appeared online (default = 1 year ago today), format YYYY/MM/DD
#' @param enddate to date appeared online (default = today), format YYYY/MM/DD
#' @import dplyr
#' @import stringr
#' @return string, a URL to search pubmed for a particular term between two given dates
#' 
gen_url_pm <- function(searchterm, 
                         startdate=as.character(Sys.Date()-365, "%Y/%m/%d"), 
                         enddate=as.character(Sys.Date(), "%Y/%m/%d")) {
  
  baseurl <- "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?"
  
  term <- searchterm %>% 
    str_replace_all(., "(\")([^\" ]+)( )([^\" ]+)(\")", "%22\\2+\\4%22") %>% 
    str_replace_all(., "(\\))", " \\1") %>%
    paste0(., " ") %>% 
    str_replace_all(., " ", "[tiab] ") %>% 
    str_replace_all(., fixed("AND[tiab]"), "AND") %>% 
    str_replace_all(., fixed("OR[tiab]"), "OR") %>% 
    str_replace_all(., fixed("NOT[tiab]"), "NOT") %>% 
    str_replace_all(., fixed(")[tiab]"), ")") %>% 
    str_squish() %>% 
    str_replace_all(., " ", "+")
  
  searchurl <- paste0(baseurl,
                      "db=pubmed&term=",term,
                      "&datetype=pdat&mindate=",startdate,"&maxdate=",enddate,
                      "&usehistory=y")
  return(searchurl)
}

#' Pubmed search
#' 
#' @param searchurl search URL generated by gen_url_pm()
#' @import httr
#' @importFrom rvest xml_nodes
#' @importFrom xml2 xml_text
#' @return A list with the total hits and history parameters for returning article info
#' 
search_pm <- function(searchurl) {
  
  keyenv <- GET(searchurl) %>%
    content() %>%
    xml_nodes("Count, QueryKey, WebEnv") %>%
    xml2::xml_text()
  
  return(list(count = keyenv[1], querykey = keyenv[2], webenv = keyenv[3]))
  
}

#' Pubmed fetch one page (up to 500 refs) from search
#' 
#' @param pagenumber number of page to retrieve
#' @param historyinfo web environment info returned from search_pm()
#' @import dplyr
#' @import purrr
#' @import tidyr
#' @import httr
#' @importFrom rvest xml_nodes
#' @importFrom xml2 xml_text xml_name
#' @return tibble with info fields on up to 500 articles
#' 
fetch_pm <- function(pagenumber, historyinfo) {
  
  url <- paste0("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&query_key=",
                historyinfo$querykey,"&WebEnv=",historyinfo$webenv,"&retmax=500&retstart=",pagenumber,"&retmode=xml")
  
  articlexml <- GET(url) %>% content() %>% xml_nodes("PubmedArticle")

  articleinfo <- map_df(articlexml, function(x) xml2tib(x, "ArticleTitle, 
                              Abstract, 
                              ArticleId[IdType=\"doi\"], 
                              Journal Title, 
                              PublicationStatus, 
                              PublicationType, 
                              PubDate Year,
                              PubDate Month,
                              PubDate Day,
                              Author LastName, 
                              Language")  %>% spread(field, value))
  
  return(articleinfo)
}

#' Pubmed all steps
#' 
#' @param searchterm text of the query
#' @param startdate from date appeared online (default = 1 year ago today), format YYYY/MM/DD
#' @param enddate to date appeared online (default = today), format YYYY/MM/DD
#' @return a tibble of results
#' 
get_pm <- function(searchterm, 
                   startdate=as.character(Sys.Date()-365, "%Y/%m/%d"), 
                   enddate=as.character(Sys.Date(), "%Y/%m/%d")) {
  
  url <- gen_url_pm(searchterm, startdate, enddate)

  search <- search_pm(url)
  
  if(as.numeric(search$count) > 0 ) {

    pages <- seq(0, search$count, 500)
  
    results <- map_df(pages, fetch_pm, search) %>%
      filter(!is.na(Year)) %>%
      mutate_at(vars(Day, Month), ~if_else(is.na(.), "01", .)) %>%
      mutate(Month = case_when(
        Month == "Jan" ~ "01",
        Month == "Feb" ~ "01",
        Month == "Mar" ~ "01",
        Month == "Apr" ~ "04",
        Month == "May" ~ "01",
        Month == "Jun" ~ "01",
        Month == "Jul" ~ "01",
        Month == "Aug" ~ "01",
        Month == "Sep" ~ "01",
        Month == "Oct" ~ "01",
        Month == "Nov" ~ "01",
        Month == "Dec" ~ "01",
        TRUE ~ Month
    )) %>%
      mutate(pdate = paste0(Year,"-",Month,"-",Day)) %>%
      mutate(type = "") %>%
      mutate(type = if_else(grepl("^Journal Article ;|; Journal Article ;|; Journal Article$|^Journal Article$", PublicationType), "journal article", type)) %>%
      mutate(type = if_else(grepl("^Review ;|; Review ;| ; Review$|^Review$", PublicationType), "review", type)) %>%
      mutate(type = if_else(type == "", "other", type)) %>%
      mutate(url = paste0("https://dx.doi.org/",ArticleId)) %>% 
      select(doi = ArticleId,
             title = ArticleTitle,
             abstract = Abstract,
             author = LastName,
             `publication date` = pdate,
             `publication type` = type,
             journal = Title,
             lang = Language, 
             url)
    
  } else {
    
    results <- tibble()
    
  }
  
  return(results)
  
}

#' Make URL for Springer API
#' 
#' @param searchterm text of query
#' @param datefrom earliest date added
#' @param dateto latest date added
#' @param apikey Springer API key
#' @import stringr
#' 
gen_url_springer <- function(searchterm,
                             datefrom = as.character(Sys.Date() - 365),
                             dateto = as.character(Sys.Date()),
                             apikey = Sys.getenv("SPRINGER_API")) {
  
  baseurl <- "http://api.springernature.com/meta/v2/json?"

  terms <- searchterm %>% 
    str_split(., " AND | OR | NOT ") %>% 
    .[[1]] %>% 
    str_remove_all(., "[\\(\\)]") %>% 
    str_replace_all(., "\"", "%22") %>%
    map_chr(., str_squish) %>% 
    str_c(., collapse = "|") %>% 
    paste0("(",.,")")
  
  term <- searchterm %>%
    str_replace_all(., "\"", "%22") %>%
    str_replace_all(., terms, "title:\\1") %>% 
    str_replace_all(., " ", "+") 
  
  searchurl <- paste0(baseurl,
                      "q=",term,"+onlinedatefrom:",datefrom,"+onlinedateto:",dateto,
                      "&api_key=",apikey)
  return(searchurl)
}

#' Springer fetch 1 page (up to 100 per page)
#' 
#' @param searchurl URL with the search query
#' @param page page to fetch
#' @import dplyr
#' @importFrom jsonlite fromJSON
#' @import purrr
#' @import httr
#' 
get_results_springer <- function(page, searchurl) {

    pagurl <- paste0(searchurl,"&p=100&s=",page)
    
    fullspring <- GET(pagurl) %>% 
      content(., "text") %>% 
      fromJSON() %>% 
      .$records %>% 
      as_tibble() %>% 
      select(url, title, creators, publicationName, doi, publicationDate, publicationType,
             genre, abstract) %>% 
      mutate_at(vars(url, creators, genre), ~as.list(.))
    
    return(fullspring)
  }
  
  
#' Springer all steps
#'  
#' @param searchterm text of query
#' @param datefrom earliest date added
#' @param dateto latest date added
#' @param apikey Springer API key
#' @return a tibble with 11 columns    

get_springer <- function(searchterm,
                         datefrom = as.character(Sys.Date() - 365),
                         dateto = as.character(Sys.Date()),
                         apikey = Sys.getenv("SPRINGER_API"))  {
  
  searchurl <- gen_url_springer(searchterm)

  total <- GET(searchurl) %>% 
    content(., "text") %>% 
    fromJSON() %>% 
    .$result %>% .$total 
  
  if(as.numeric(total) > 0) {
  
    # paginate
    
    pages <- seq(1, total, 100)
    
    # map across pages
    
    result <- map_df(pages, get_results_springer, searchurl = searchurl)
  
    # clean
      
      urls <- result %>% 
        group_by(doi) %>% 
        unnest(cols = "url") %>% 
        filter(format == "html") %>% 
        ungroup() %>% 
        select(doi, url = value) 
  
      authors <- result %>% 
        group_by(doi) %>%
        unnest(cols = "creators") %>%
        mutate(createlist = paste0(creator, collapse = " ; ")) %>%
        select(-creator) %>%
        ungroup() %>%
        unique() %>%
        select(doi, author = createlist)
  
      types <- result %>% 
        group_by(doi) %>%
        select(doi, publicationType, genre) %>%
        unnest(cols = "genre") %>%
        mutate(genre = paste0(genre, collapse = " ; ")) %>%
        unique() %>%
        mutate(type = "") %>%
        mutate(type = if_else(publicationType == "Journal" &
                                grepl("original( )?paper|^article$|original( )?article|research( )?article|^research$|research( )?paper|original( )?contribution",
                                      genre, ignore.case = T),
                              "journal article", type)) %>%
        mutate(type = if_else(publicationType == "Journal" &
                                grepl("review( )?paper|review( )?article|invited( )review|^review$",
                                      genre, ignore.case = T),
                              "review", type)) %>%
        mutate(type = if_else(type == "", "other", type)) %>%
        select(-genre) %>%
        unique() %>%
        ungroup()
      
      result <- result %>%
        left_join(urls, by = "doi") %>%
         left_join(authors, by = "doi") %>%
         left_join(types, by = "doi") %>%
         select(doi,
                title,
                abstract,
                author,
                `publication date` = publicationDate,
                `publication type` = type,
                journal = publicationName,
                url = url.y) %>% 
        mutate(source = "Springer")

  
   } else {
  
     result <- tibble()
  
   }
  
   return(result)
  
}



